eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
      - id: movie_info_route
        uri: lb://movie-info-service
        predicates:
        - Path=/movies/**
      - id: movie_catalog_route
        uri: lb://movie-catalog-service
        predicates:
        - Path=/catalog/**
management:
  endpoints:
    web:
      exposure:
        include: "*"